classify_data_quality_task:
  description: >
    Faça uma auditoria completa na base de dados transacionais do e-commerce apresentada abaixo:

    {dataframe}

    Verifique colunas com valores nulos, inconsistentes ou com padrões inesperados,
    especialmente em campos como ID do cliente, valor do pedido, data da transação, categoria de produto
    ou status de pagamento.

  expected_output: >
    Um relatório textual com os principais problemas de qualidade encontrados, como colunas vazias,
    formatos inconsistentes ou dados fora do esperado em um contexto de e-commerce.

generate_insights_task:
  description: >
    Gere um relatório de insights estratégicos com base em todos os dados transacionais do e-commerce apresentados a seguir:

    Considere aspectos como:
    - Produtos mais vendidos e menos vendidos
    - Ticket médio por cliente ou por pedido
    - Categorias com maior ou menor receita
    - Clientes de alto valor ou churn
    - Canais de aquisição mais eficazes
    - Frequência e recorrência de compra
    - Descontos aplicados e sua efetividade

    Objetivo informado pelo usuário:
    {objetivo}

    Base de dados:
    {dataframe}

  expected_output: >
    De 3 a 5 insights claros, relevantes e aplicáveis ao negócio,
    com sugestões para aumentar vendas, otimizar campanhas ou melhorar a experiência do cliente.

qa_on_dataframe_task:
  description: >
    O usuário fez a seguinte pergunta com base na base de dados completa do e-commerce:

    Pergunta: {pergunta}

    Base de dados fornecida:
    {dataframe}

  expected_output: >
    Uma resposta direta, objetiva e embasada apenas nos dados fornecidos.
    Sempre que possível, cite números, totais, médias ou percentuais com clareza.

describe_charts_task:
  description: >
    O gráfico a seguir representa dados de vendas, produtos ou clientes no contexto de um e-commerce.

    Título: {titulo}
    Eixo X: {x_col}
    Eixo Y: {y_col}

    Segmento dos dados utilizados para gerar o gráfico:
    {amostra}

  expected_output: >
    Uma descrição clara em até 3 frases, destacando padrões, picos ou correlações observadas.
    Se houver um insight comercial evidente (ex: vendas maiores em datas específicas ou categorias dominantes), mencione.
